### ISSUE TITLE
Expanding the allowed file extensions list

### ISSUE THREAD

**Issue by jlamarque34** [ncbo/owlapi_wrapper#12]
While parsing from within an input directory, only *.obo|*.owl|*.ttl|*.xml files are taken into account, the others being filtered (see the class below).

> https://github.com/ncbo/owlapi_wrapper/blob/master/src/main/java/org/stanford/ncbo/oapiwrapper/OntologySuffixFileFilter.java

It would be nice to expand the allowed extensions list with the following : *.n3, *.nt, *.nq, *.skos, *.rdf, *.rdfs

**Comment by jvendetti** [comment]
This was fixed by a pull request: https://github.com/ncbo/owlapi_wrapper/pull/13
