### ISSUE TITLE
Add IRI mapper for SKOS Core Vocabulary to prevent missing import errors

### ISSUE THREAD

**Issue by jvendetti** [ncbo/owlapi_wrapper#22]
As of recently, the W3C started rate limiting requests to http://www.w3.org/2004/02/skos/core:

> We recently adjusted our abuse prevention systems to address an excessive volume of requests from automated systems, adding up to tens of millions of requests per day.

As a side effect of this, attempting to load ontologies in BioPortal that import SKOS Core, e.g.:

```rdf
<owl:imports rdf:resource="http://www.w3.org/2004/02/skos/core"/>
```

.... result in missing import errors in the logs:

```
++++++++++++++++++++++++++++++++++++++++++++++++++
Error: OWL_IMPORT_MISSING
Message: http://www.w3.org/2004/02/skos/core
++++++++++++++++++++++++++++++++++++++++++++++++++
```

... and intermittently failing metrics-related unit tests in the ontologies_linked_data project. See this issue: https://github.com/ontoportal/ontologies_linked_data/issues/6.

Since this is an oft-imported vocabulary, I propose an initial solution of using an IRI mapper that maps to a copy of the file that we host somewhere.

**Comment by jvendetti** [comment]
@alexskr - any opinion on where our copy of `skos.rdf` should live?

**Comment by alexskr** [comment]
do you know if there a way to specify local file system path instead of a web address.  
Or maybe we can host skos core in BioPortal?

**Comment by jvendetti** [comment]
The example code provided by the OWL API shows that you can use a local file system path. I tested it and it seems to work - at least in a simple unit test scenario:

```java
@Test
public void testSimpleIRIMapper() throws Exception {
  IRI skosCoreIRI = IRI.create("http://www.w3.org/2004/02/skos/core");
  IRI skosCoreDocumentIRI = IRI.create("file:/Users/vendetti/Downloads/skos.rdf");
  SimpleIRIMapper mapper = new SimpleIRIMapper(skosCoreIRI, skosCoreDocumentIRI);

  OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
  manager.getIRIMappers().add(mapper);

  File broFile = new File("src/test/resources/BRO_v3.2.owl");
  FileDocumentSource fileDocumentSource = new FileDocumentSource(broFile);
  OWLOntology ontology = manager.loadOntologyFromOntologyDocument(fileDocumentSource);
  assertNotNull(ontology);
}
```

So I take it that means you'd prefer to have it embedded?

**Comment by alexskr** [comment]
embedding file should reduce overall complexity and improve resiliency against potential external resource connectivity issues.
